### ISSUE TITLE
Username not defined

### ISSUE THREAD

**Issue by Mvpchris** [theraspberryguy/siricontrol#1]
Ok Im trying to run the script. I get an error saying 
NameError: name '(My Username)' is not defined.

Im using python 2.7.10 if that has anything to do with it. Could you put up an example of how to username/password should be inserted into your file? Like use a fake username and password? I didn't want to upload exactly how my file looks because my email info is on there obviously.

Once complete this I will try to talk to jasper but I wanted to make sure this works first

**Comment by theraspberryguy** [comment]
I am sorry I forgot to make it clear but this code is written for python 3 onwards. I have updated the README now. However, if you are using a Raspberry Pi, Raspbian comes with python 3. Try running the script from the python 3 IDLE. Thanks for letting me know about the problem.

**Comment by Mvpchris** [comment]
[hello.txt](https://github.com/theraspberryguy/siricontrol/files/924796/hello.txt)

Latest error I'm receiving:

    latest_email_id = uidlist[0].split()[-1]
IndexError: list index out of range

I updated my python to the latest version like you instructed.

**Comment by theraspberryguy** [comment]
That means that there are no Notes in your account. Try adding a few notes through the Notes app or Siri to your gmail account, as I suggested in my post. As there are no Notes, the index is out of range. Now, it should definitely work as login must have been successful and should see your Siri commands being printed in the IDLE console.

**Comment by theraspberryguy** [comment]
@Mvpchris Have you had any success with this script?

**Comment by Mvpchris** [comment]
The script worked for one day. When I tried to run the program again today using siri it didn't work for some reason even though I didn't adjust the code. Tomorrow I'm going to try it again and keep you updated. Thank you for getting me this far though. Huge help!!

**Comment by theraspberryguy** [comment]
@Mvpchris This is usually caused due to syncing issues between the Notes app and gmail account and happens sometimes. This is because of Apple and not in my hands. Just delete the Notes label from the gmail account and after a while, it should come back and syncing properly.  

Then try talking to jasper through siri, which is quite simple as you have set up your account and device: https://thereallycoolstuff.wordpress.com/talking-to-jasper-using-siri/
